import flet as ft

DROPDOWN = "DropDown"
TEXTFIELD = "TextField"

dicts = {
    'Dense': {
        'units': 0,
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'bias_constraint': None,
        'lora_rank': None,
        'color':ft.colors.AMBER
    },
    'Input': {
        'shape': None,
        'batch_size': None,
        'dtype': None,
        'sparse': None,
        'batch_shape': None,
        'name': None,
        'tensor': None,
        'color':ft.colors.GREY
    },
    'Activation': {
        'activation': None,
        'color':ft.colors.YELLOW
    },
    'Embedding': {
        'input_dim': None,
        'output_dim': None,
        'embeddings_initializer': 'uniform',
        'embeddings_regularizer': None,
        'embeddings_constraint': None,
        'mask_zero': False,
        'weights': None,
        'lora_rank': None,
        'color':ft.colors.BLACK
    },
    'Conv1D': {
        'filters': None,
        'kernel_size': None,
        'strides': 1,
        'padding': 'valid',
        'data_format': None,
        'dilation_rate': 1,
        'groups': 1,
        'activation': None,
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'bias_constraint': None,
        'color':ft.colors.GREEN
    },
    'Conv2D': {
        'filters': None,
        'kernel_size': None,
        'strides': (1, 1),
        'padding': 'valid',
        'data_format': None,
        'dilation_rate': (1, 1),
        'groups': 1,
        'activation': None,
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'bias_constraint': None,
        'color':ft.colors.GREEN_100
    },
    'Conv3D': {
        'filters': None,
        'kernel_size': None,
        'strides': (1, 1, 1),
        'padding': 'valid',
        'data_format': None,
        'dilation_rate': (1, 1, 1),
        'groups': 1,
        'activation': None,
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'bias_constraint': None,
        'color':ft.colors.GREEN_200
    },
    'MaxPooling1D': {
        'pool_size': 2,
        'strides': None,
        'padding': 'valid',
        'data_format': None,
        'name': None,
        'color':ft.colors.BLUE
    },
    'MaxPooling2D': {
        'pool_size': (2, 2),
        'strides': None,
        'padding': 'valid',
        'data_format': None,
        'name': None,
        'color':ft.colors.BLUE_100
    },
    'MaxPooling3D': {
        'pool_size': (2, 2, 2),
        'strides': None,
        'padding': 'valid',
        'data_format': None,
        'name': None,
        'color':ft.colors.BLUE_200
    },
    'AveragePooling1D': {
        'pool_size': None,
        'strides': None,
        'padding': 'valid',
        'data_format': None,
        'name': None,
        'color':ft.colors.BLUE_GREY
    },
    'AveragePooling2D': {
        'pool_size': None,
        'strides': None,
        'padding': 'valid',
        'data_format': None,
        'name': None,
        'color':ft.colors.BLUE_GREY_100
    },
    'AveragePooling3D': {
        'pool_size': None,
        'strides': None,
        'padding': 'valid',
        'data_format': None,
        'name': None,
        'color':ft.colors.BLUE_GREY_200
    },
    'GlobalMaxPooling1D': {
        'data_format': None,
        'keepdims': False,
        'color':ft.colors.BLUE_ACCENT
    },
    'GlobalMaxPooling2D': {
        'data_format': None,
        'keepdims': False,
        'color':ft.colors.BLUE_ACCENT_100
    },
    'GlobalMaxPooling3D': {
        'data_format': None,
        'keepdims': False,
        'color':ft.colors.BLUE_ACCENT_200
    },
    'GlobalAveragePooling1D': {
        'data_format': None,
        'keepdims': False,
        'color':ft.colors.BLUE_500
    },
    'GlobalAveragePooling2D': {
        'data_format': None,
        'keepdims': False,
        'color':ft.colors.BLUE_600
    },
    'GlobalAveragePooling3D': {
        'data_format': None,
        'keepdims': False,
        'color':ft.colors.BLUE_700
    },
    'LSTM': {
        'units': None,
        'activation': 'tanh',
        'recurrent_activation': 'sigmoid',
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'recurrent_initializer': 'orthogonal',
        'bias_initializer': 'zeros',
        'unit_forget_bias': True,
        'kernel_regularizer': None,
        'recurrent_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'recurrent_constraint': None,
        'bias_constraint': None,
        'dropout': 0.0,
        'recurrent_dropout': 0.0,
        'seed': None,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'unroll': False,
        'use_cudnn': 'auto',
        'color':ft.colors.DEEP_ORANGE
    },
    'GRU': {
        'units': None,
        'activation': 'tanh',
        'recurrent_activation': 'sigmoid',
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'recurrent_initializer': 'orthogonal',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'recurrent_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'recurrent_constraint': None,
        'bias_constraint': None,
        'dropout': 0.0,
        'recurrent_dropout': 0.0,
        'seed': None,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'unroll': False,
        'reset_after': True,
        'use_cudnn': 'auto',
        'color':ft.colors.INDIGO
    },
    'SimpleRNN': {
        'units': None,
        'activation': 'tanh',
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'recurrent_initializer': 'orthogonal',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'recurrent_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'recurrent_constraint': None,
        'bias_constraint': None,
        'dropout': 0.0,
        'recurrent_dropout': 0.0,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'unroll': False,
        'seed': None,
        'color':ft.colors.LIME
    },
    'Bidirectional': {
        'layer': None,
        'merge_mode': 'concat',
        'weights': None,
        'backward_layer': None,
        'color':ft.colors.RED
    },
    'ConvLSTM1D': {
        'filters': None,
        'kernel_size': None,
        'strides': 1,
        'padding': 'valid',
        'data_format': None,
        'dilation_rate': 1,
        'activation': 'tanh',
        'recurrent_activation': 'sigmoid',
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'recurrent_initializer': 'orthogonal',
        'bias_initializer': 'zeros',
        'unit_forget_bias': True,
        'kernel_regularizer': None,
        'recurrent_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'recurrent_constraint': None,
        'bias_constraint': None,
        'dropout': 0.0,
        'recurrent_dropout': 0.0,
        'seed': None,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'color':ft.colors.ORANGE
    },
    'ConvLSTM2D': {
        'filters': None,
        'kernel_size': None,
        'strides': 1,
        'padding': 'valid',
        'data_format': None,
        'dilation_rate': 1,
        'activation': 'tanh',
        'recurrent_activation': 'sigmoid',
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'recurrent_initializer': 'orthogonal',
        'bias_initializer': 'zeros',
        'unit_forget_bias': True,
        'kernel_regularizer': None,
        'recurrent_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'recurrent_constraint': None,
        'bias_constraint': None,
        'dropout': 0.0,
        'recurrent_dropout': 0.0,
        'seed': None,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'color':ft.colors.BROWN
    },
    'ConvLSTM3D': {
        'filters': None,
        'kernel_size': None,
        'strides': 1,
        'padding': 'valid',
        'data_format': None,
        'dilation_rate': 1,
        'activation': 'tanh',
        'recurrent_activation': 'sigmoid',
        'use_bias': True,
        'kernel_initializer': 'glorot_uniform',
        'recurrent_initializer': 'orthogonal',
        'bias_initializer': 'zeros',
        'unit_forget_bias': True,
        'kernel_regularizer': None,
        'recurrent_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'recurrent_constraint': None,
        'bias_constraint': None,
        'dropout': 0.0,
        'recurrent_dropout': 0.0,
        'seed': None,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'color':ft.colors.ON_SURFACE
    },
    'RNN': {
        'cell': None,
        'return_sequences': False,
        'return_state': False,
        'go_backwards': False,
        'stateful': False,
        'unroll': False,
        'zero_output_for_mask': False,
        'color':ft.colors.PINK
    },
    'BatchNormalization': {
        'axis': -1,
        'momentum': 0.99,
        'epsilon': 0.001,
        'center': True,
        'scale': True,
        'beta_initializer': 'zeros',
        'gamma_initializer': 'ones',
        'moving_mean_initializer': 'zeros',
        'moving_variance_initializer': 'ones',
        'beta_regularizer': None,
        'gamma_regularizer': None,
        'beta_constraint': None,
        'gamma_constraint': None,
        'synchronized': False,
        'color':ft.colors.GREY_600
    },
    'LayerNormalization': {
        'axis': -1,
        'epsilon': 0.001,
        'center': True,
        'scale': True,
        'rms_scaling': False,
        'beta_initializer': 'zeros',
        'gamma_initializer': 'ones',
        'beta_regularizer': None,
        'gamma_regularizer': None,
        'beta_constraint': None,
        'gamma_constraint': None,
        'color':ft.colors.PURPLE
    },
    'Dropout': {
        'rate': None,
        'noise_shape': None,
        'seed': None,
        'color':ft.colors.BLACK
    },
    'SpatialDropout1D': {
        'rate': None,
        'seed': None,
        'name': None,
        'dtype': None,
        'color':ft.colors.CYAN
    },
    'SpatialDropout2D': {
        'rate': None,
        'data_format': None,
        'seed': None,
        'name': None,
        'dtype': None,
        'color':ft.colors.CYAN
    },
    'SpatialDropout3D': {
        'rate': None,
        'data_format': None,
        'seed': None,
        'name': None,
        'dtype': None,
        'color':ft.colors.CYAN
    },
    'MultiHeadAttention': {
        'num_heads': None,
        'key_dim': None,
        'value_dim': None,
        'dropout': 0.0,
        'use_bias': True,
        'output_shape': None,
        'attention_axes': None,
        'kernel_initializer': 'glorot_uniform',
        'bias_initializer': 'zeros',
        'kernel_regularizer': None,
        'bias_regularizer': None,
        'activity_regularizer': None,
        'kernel_constraint': None,
        'bias_constraint': None,
        'color':ft.colors.CYAN
    },
    'Attention': {
        'use_scale': False,
        'score_mode': 'dot',
        'dropout': 0.0,
        'seed': None,
        'color':ft.colors.CYAN
    },
    'Reshape': {
        'target_shape': None,
        'color':ft.colors.CYAN
    },
    'Flatten': {
        'data_format': None,
        'color':ft.colors.CYAN
    },

}

